# Generated by Django 5.2.5 on 2025-08-07 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentQuizQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.question')),
                ('student_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.studentquiz')),
            ],
            options={
                'unique_together': {('student_quiz', 'question')},
            },
        ),
    ]
