# Generated by Django 4.2.14 on 2025-08-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_studentquizquestions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentquizquestions',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='submission',
            name='score',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='is_public',
        ),
        migrations.AddField(
            model_name='submission',
            name='score_awarded',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('mcq', 'Multiple Choice'), ('tf', 'True/False'), ('code', 'Coding')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentquiz',
            name='total_score',
            field=models.FloatField(default=0),
        ),
    ]
