# Generated by Django 4.2.14 on 2025-08-11 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_alter_studentquizquestions_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_text_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='sample_input',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='sample_output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='output_received',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentquizquestions',
            name='student_quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_questions', to='quizzes.studentquiz'),
        ),
        migrations.AddConstraint(
            model_name='studentquiz',
            constraint=models.UniqueConstraint(condition=models.Q(('completed_at__isnull', True)), fields=('student', 'quiz'), name='unique_active_quiz_attempt'),
        ),
    ]
