# Generated by Django 4.2.14 on 2025-08-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_question_correct_text_answer_question_sample_input_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentquiz',
            name='unique_active_quiz_attempt',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('mcq', 'Multiple Choice'), ('tf', 'True/False'), ('code', 'Coding'), ('fill', 'Fill in the blank')], default='text', max_length=10),
        ),
        migrations.AddIndex(
            model_name='studentquiz',
            index=models.Index(fields=['student', 'quiz'], name='quizzes_stu_student_51af80_idx'),
        ),
    ]
