# Generated by Django 4.2.14 on 2025-08-13 18:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0006_remove_studentquiz_unique_active_quiz_attempt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentquiz',
            name='answer_sheet',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentquiz',
            name='result_summary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentquiz',
            name='time_taken_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentquiz',
            name='total_points',
            field=models.FloatField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='studentquiz',
            unique_together={('student', 'quiz')},
        ),
    ]
