# Generated by Django 4.2.14 on 2025-08-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_alter_question_options_question_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquizquestions',
            name='selected_choices',
            field=models.ManyToManyField(blank=True, related_name='student_selected_choices', to='quizzes.choice'),
        ),
    ]
