# Generated by Django 5.2.3 on 2025-08-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_studentquizquestions_selected_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquiz',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
