# Generated by Django 4.2.14 on 2025-08-15 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0009_studentquiz_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.JSONField(blank=True, null=True)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('code_submitted', models.TextField(blank=True, null=True)),
                ('graded_score', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StudentQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted', models.BooleanField(default=False)),
                ('submission_time', models.DateTimeField(blank=True, null=True)),
                ('total_score', models.FloatField(default=0)),
                ('total_possible_points', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.RemoveIndex(
            model_name='studentquiz',
            name='quizzes_stu_student_51af80_idx',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='correct_text_answer',
            new_name='problem_statement',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='score_awarded',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='user',
            new_name='student',
        ),
        migrations.AlterUniqueTogether(
            name='studentquiz',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='submission',
            name='answer_text',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='output_received',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='question',
        ),
        migrations.AddField(
            model_name='quiz',
            name='max_attempts',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quiz',
            name='random_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='total_marks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentquizquestions',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('tf', 'True/False'), ('text', 'Text'), ('code', 'Coding')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentquizquestions',
            name='selected_choices',
            field=models.ManyToManyField(blank=True, to='quizzes.choice'),
        ),
        migrations.AlterField(
            model_name='studentquizquestions',
            name='student_quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.studentquiz'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_testcases', to='quizzes.question'),
        ),
        migrations.AddField(
            model_name='studentquizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz'),
        ),
        migrations.AddField(
            model_name='studentquizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.studentquizattempt'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.question'),
        ),
        migrations.RemoveField(
            model_name='studentquiz',
            name='answer_sheet',
        ),
        migrations.RemoveField(
            model_name='studentquiz',
            name='result_summary',
        ),
        migrations.RemoveField(
            model_name='studentquiz',
            name='submitted',
        ),
        migrations.RemoveField(
            model_name='studentquiz',
            name='time_taken_seconds',
        ),
        migrations.RemoveField(
            model_name='studentquiz',
            name='total_points',
        ),
    ]
