# Generated by Django 4.2.14 on 2025-08-17 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_answer_studentquizattempt_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='quizzes.question'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('attempt', 'question')},
        ),
    ]
